### PR TITLE
Fix bug where non-order keyword arguments are passed from `sort!` to `searchsortedfirst`

### LINKED ISSUE #334: SparseArrays sort! function returning kwargs is breaking searchsortedfirst
There seems to be a problem with the searchsortedfirst function accepting only by, lt and rev as keywords but receiving the complete kwargs from the the sort! function. the alg parameter that sort! can utilize, is not supported by the searchsortedfirst function. Can this be fixed/adapted?
commit: 57cbb74868a9811bd1a48cbe6f786e8f4050f5a3

<details>
<summary> Error message: </summary>

```
  MethodError: no method matching searchsortedfirst(::Vector{Float64}, ::Float64; alg::Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}})
  
  Closest candidates are:
    searchsortedfirst(::AbstractVector, ::Any; lt, by, rev, order) got unsupported keyword argument "alg"
     @ Base sort.jl:285
    searchsortedfirst(::AbstractVector, ::Any, ::T, ::T, ::Base.Order.Ordering) where T<:Integer got unsupported keyword argument "alg"
     @ Base sort.jl:164
    searchsortedfirst(::AbstractVector, ::Any, ::Base.Order.Ordering) got unsupported keyword argument "alg"
     @ Base sort.jl:283
    ...
  
  Stacktrace:
    [1] kwerr(::NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}, ::Function, ::Vector{Float64}, ::Float64)
      @ Base ./error.jl:165
    [2] kwcall(::NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}, ::typeof(searchsortedfirst), v::Vector{Float64}, x::Float64)
      @ Base.Sort ./sort.jl:285
    [3] sort!(x::SparseArrays.SparseVector{Float64, Int64}; kws::Base.Pairs{Symbol, Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Tuple{Symbol}, NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}})
      @ SparseArrays /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/SparseArrays/src/sparsevector.jl:2137
    [4] kwcall(::NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}, ::typeof(sort!), x::SparseArrays.SparseVector{Float64, Int64})
      @ SparseArrays /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/SparseArrays/src/sparsevector.jl:2134
    [5] sort(v::SparseArrays.SparseVector{Float64, Int64}; kws::Base.Pairs{Symbol, Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Tuple{Symbol}, NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}})
      @ Base.Sort ./sort.jl:1396
    [6] kwcall(::NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}, ::typeof(sort), v::SparseArrays.SparseVector{Float64, Int64})
      @ Base.Sort ./sort.jl:1396
    [7] addcounts_radixsort!(cm::Dict{Float64, Int64}, x::SparseArrays.SparseVector{Float64, Int64})
      @ StatsBase ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:385
    [8] #_addcounts!#96
      @ ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:276 [inlined]
    [9] #addcounts!#95
      @ ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:270 [inlined]
   [10] countmap(x::SparseArrays.SparseVector{Float64, Int64}; alg::Symbol)
      @ StatsBase ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:442
   [11] countmap(x::SparseArrays.SparseVector{Float64, Int64})
      @ StatsBase ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:442
   [12] atom_conjugated_system_processor(allCycles_vec::Vector{Vector{Int64}}, mol::Molecule{Float32})
      @ BiochemicalAlgorithms ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/src/core/atomtyping/preprocessing_molecule.jl:138
   [13] PreprocessingMolecule!(mol::Molecule{Float32})
      @ BiochemicalAlgorithms ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/src/core/atomtyping/preprocessing_molecule.jl:23
   [14] macro expansion
      @ ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/test/test_preprocessing.jl:4 [inlined]
   [15] macro expansion
      @ /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/Test/src/Test.jl:1502 [inlined]
   [16] top-level scope
      @ ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/test/test_preprocessing.jl:3
   [17] include(fname::String)
      @ Base.MainInclude ./client.jl:478
   [18] macro expansion
      @ ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/test/runtests.jl:23 [inlined]
   [19] macro expansion
      @ /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/Test/src/Test.jl:1502 [inlined]
   [20] macro expansion
      @ ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/test/runtests.jl:23 [inlined]
   [21] macro expansion
      @ /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/Test/src/Test.jl:1502 [inlined]
   [22] top-level scope
      @ ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/test/runtests.jl:6
   [23] include(fname::String)
      @ Base.MainInclude ./client.jl:478
   [24] top-level scope
      @ none:6
   [25] eval
      @ ./boot.jl:370 [inlined]
   [26] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:280
   [27] _start()
      @ Base ./client.jl:522
Clear_Preprocessing_Molecule: Error During Test at /home/runner/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/test/test_preprocessing.jl:17
  Got exception outside of a @test
  MethodError: no method matching searchsortedfirst(::Vector{Float64}, ::Float64; alg::Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}})
  
  Closest candidates are:
    searchsortedfirst(::AbstractVector, ::Any; lt, by, rev, order) got unsupported keyword argument "alg"
     @ Base sort.jl:285
    searchsortedfirst(::AbstractVector, ::Any, ::T, ::T, ::Base.Order.Ordering) where T<:Integer got unsupported keyword argument "alg"
     @ Base sort.jl:164
    searchsortedfirst(::AbstractVector, ::Any, ::Base.Order.Ordering) got unsupported keyword argument "alg"
     @ Base sort.jl:283
    ...
  
  Stacktrace:
    [1] kwerr(::NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}, ::Function, ::Vector{Float64}, ::Float64)
      @ Base ./error.jl:165
    [2] kwcall(::NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}, ::typeof(searchsortedfirst), v::Vector{Float64}, x::Float64)
      @ Base.Sort ./sort.jl:285
    [3] sort!(x::SparseArrays.SparseVector{Float64, Int64}; kws::Base.Pairs{Symbol, Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Tuple{Symbol}, NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}})
      @ SparseArrays /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/SparseArrays/src/sparsevector.jl:2137
    [4] kwcall(::NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}, ::typeof(sort!), x::SparseArrays.SparseVector{Float64, Int64})
      @ SparseArrays /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/SparseArrays/src/sparsevector.jl:2134
    [5] sort(v::SparseArrays.SparseVector{Float64, Int64}; kws::Base.Pairs{Symbol, Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Tuple{Symbol}, NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}})
      @ Base.Sort ./sort.jl:1396
    [6] kwcall(::NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}, ::typeof(sort), v::SparseArrays.SparseVector{Float64, Int64})
      @ Base.Sort ./sort.jl:1396
    [7] addcounts_radixsort!(cm::Dict{Float64, Int64}, x::SparseArrays.SparseVector{Float64, Int64})
      @ StatsBase ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:385
    [8] #_addcounts!#96
      @ ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:276 [inlined]
    [9] #addcounts!#95
      @ ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:270 [inlined]
   [10] countmap(x::SparseArrays.SparseVector{Float64, Int64}; alg::Symbol)
      @ StatsBase ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:442
   [11] countmap(x::SparseArrays.SparseVector{Float64, Int64})
      @ StatsBase ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:442
   [12] atom_conjugated_system_processor(allCycles_vec::Vector{Vector{Int64}}, mol::Molecule{Float32})
      @ BiochemicalAlgorithms ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/src/core/atomtyping/preprocessing_molecule.jl:138
   [13] PreprocessingMolecule!(mol::Molecule{Float32})
      @ BiochemicalAlgorithms ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/src/core/atomtyping/preprocessing_molecule.jl:23
   [14] macro expansion
      @ ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/test/test_preprocessing.jl:27 [inlined]
   [15] macro expansion
      @ /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/Test/src/Test.jl:1502 [inlined]
   [16] top-level scope
      @ ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/test/test_preprocessing.jl:18
   [17] include(fname::String)
      @ Base.MainInclude ./client.jl:478
   [18] macro expansion
      @ ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/test/runtests.jl:23 [inlined]
   [19] macro expansion
      @ /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/Test/src/Test.jl:1502 [inlined]
   [20] macro expansion
      @ ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/test/runtests.jl:23 [inlined]
   [21] macro expansion
      @ /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/Test/src/Test.jl:1502 [inlined]
   [22] top-level scope
      @ ~/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/test/runtests.jl:6
   [23] include(fname::String)
      @ Base.MainInclude ./client.jl:478
   [24] top-level scope
      @ none:6
   [25] eval
      @ ./boot.jl:370 [inlined]
   [26] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:280
   [27] _start()
      @ Base ./client.jl:522
gaff_atomtyping_complete_script: Error During Test at /home/runner/work/BiochemicalAlgorithms.jl/BiochemicalAlgorithms.jl/test/test_atomtyping.jl:37
  Got exception outside of a @test
  MethodError: no method matching searchsortedfirst(::Vector{Float64}, ::Float64; alg::Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}})
  
  Closest candidates are:
    searchsortedfirst(::AbstractVector, ::Any; lt, by, rev, order) got unsupported keyword argument "alg"
     @ Base sort.jl:285
    searchsortedfirst(::AbstractVector, ::Any, ::T, ::T, ::Base.Order.Ordering) where T<:Integer got unsupported keyword argument "alg"
     @ Base sort.jl:164
    searchsortedfirst(::AbstractVector, ::Any, ::Base.Order.Ordering) got unsupported keyword argument "alg"
     @ Base sort.jl:283
    ...
  
  Stacktrace:
    [1] kwerr(::NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}, ::Function, ::Vector{Float64}, ::Float64)
      @ Base ./error.jl:165
    [2] kwcall(::NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}, ::typeof(searchsortedfirst), v::Vector{Float64}, x::Float64)
      @ Base.Sort ./sort.jl:285
    [3] sort!(x::SparseArrays.SparseVector{Float64, Int64}; kws::Base.Pairs{Symbol, Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Tuple{Symbol}, NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}})
      @ SparseArrays /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/SparseArrays/src/sparsevector.jl:2137
    [4] kwcall(::NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}, ::typeof(sort!), x::SparseArrays.SparseVector{Float64, Int64})
      @ SparseArrays /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/SparseArrays/src/sparsevector.jl:2134
    [5] sort(v::SparseArrays.SparseVector{Float64, Int64}; kws::Base.Pairs{Symbol, Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Tuple{Symbol}, NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}})
      @ Base.Sort ./sort.jl:1396
    [6] kwcall(::NamedTuple{(:alg,), Tuple{Base.Sort.MissingOptimization{Base.Sort.BoolOptimization{Base.Sort.Small{10, Base.Sort.InsertionSortAlg, Base.Sort.IEEEFloatOptimization{Base.Sort.IsUIntMappable{Base.Sort.Small{40, Base.Sort.InsertionSortAlg, Base.Sort.CheckSorted{Base.Sort.ComputeExtrema{Base.Sort.ConsiderCountingSort{Base.Sort.CountingSort, Base.Sort.ConsiderRadixSort{Base.Sort.RadixSort, Base.Sort.Small{80, Base.Sort.InsertionSortAlg, Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}, Base.Sort.StableCheckSorted{Base.Sort.ScratchQuickSort{Missing, Missing, Base.Sort.InsertionSortAlg}}}}}}}}}, ::typeof(sort), v::SparseArrays.SparseVector{Float64, Int64})
      @ Base.Sort ./sort.jl:1396
    [7] addcounts_radixsort!(cm::Dict{Float64, Int64}, x::SparseArrays.SparseVector{Float64, Int64})
      @ StatsBase ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:385
    [8] #_addcounts!#96
      @ ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:276 [inlined]
    [9] #addcounts!#95
      @ ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:270 [inlined]
   [10] countmap(x::SparseArrays.SparseVector{Float64, Int64}; alg::Symbol)
      @ StatsBase ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:442
   [11] countmap(x::SparseArrays.SparseVector{Float64, Int64})
      @ StatsBase ~/.julia/packages/StatsBase/XgjIN/src/counts.jl:442
```

</details>

_Edited by @LilithHafner for formatting_

### PR DESCRIPTION
**Pull request by LilithHafner**
Silently ignore unrecognized keywords when finding the first index of zero. If stray keywords are passed, they will still cause the inner `sort!` to throw.

Fixes #334

Backport because I introduced this bug in 1.9 in #303.

### CODE REVIEW

File: src/sparsevector.jl [hunk 1]
```diff
@@ -2138,11 +2138,14 @@ function _densifystarttolastnz!(x::SparseVector)
     x
 end
 
-#sorting
+#sorting TODO: integrate with `Base.Sort.IEEEFloatOptimization`'s partitioning by zero
+searchsortedfirst_discard_keywords(v::AbstractVector, x; lt=isless, by=identity,
+    rev::Union{Bool,Nothing}=nothing, order::Base.Order.Ordering=Forward, kws...) =
+        searchsortedfirst(v,x,Base.Order.ord(lt,by,rev,order))
 function sort!(x::AbstractCompressedVector; kws...)
```
Comment (dkarrasch) [inline src/sparsevector.jl:2145]: Why not apply the same trick to `sort!` directly?

Comment (LilithHafner) [reply src/sparsevector.jl:2145]: I want `sort!(sprand(10, .1), banana=:blue)` to continue to error.

Comment (dkarrasch) [reply src/sparsevector.jl:2145]: Makes sense. Judging from the code, however, I don't quite see where that call would throw.

Comment (LilithHafner) [reply src/sparsevector.jl:2145]: It should throw at `sort!(nz; kws...)`. I'll also add a test.

File: test/issues.jl [hunk 2]
```diff
@@ -783,6 +783,11 @@ g12063() = f12063(0, 0, 0, 0, 0, 0, 0.0, spzeros(0,0), Int[])
     @test String(take!(io)) == "transpose(sparse([1, 2, 1, 2], [1, 1, 2, 2], [1, 3, 2, 4], 2, 2))"
 end
 
+@testset "Issue #334" begin
+    x = sprand(10, .3);
+    @test issorted(sort!(x; alg=Base.DEFAULT_STABLE));
```
Comment (LilithHafner) [inline test/issues.jl:788]:
```suggestion
    @test issorted(sort!(x; alg=Base.DEFAULT_STABLE));
    @test_throws MethodError sort!(x; banana=:blue); # From discussion at #335
```

**Comment by ViralBShah** [comment]
Ok to merge?
